### ISSUE TITLE
Implicit data-type conversion

### ISSUE THREAD

**Issue by kant2002** [StereoDB/StereoDB#20]
We need provide support for implicit type conversion, since I can guarantee we will have a lot of pissing of users. Example
```sql
CREATE TABLE Data(
   Id int32 not null,
   Code int64 not null
) 
```

Let's say we will write following query
```
SELECT * from Data WHERE Id = Code
```

This may blow up in runtime, since we will write filter approximately like this
```
let filter row =
    let a = row.Id
    let b = row.Code
    let result = Data.operator == (Int32, Int32)
    result
```

In this case runtime may properly perform conversion for us, but what about other datatypes? For example string and int comparison, or int and float. float and datetime.

Currently SQL compiler build expression type based on the type of the column and have fixed type for constants. If we wrote rules for the data type conversions, implicit and explicit we should transform original expression and insert casts in the SqlExpression where appropriate.

**Comment by AntyaDev** [comment]
I got you. It sounds reasonable but I would delay this functionality since it's not critical for now.
