### ISSUE TITLE
Move SQL support to StereoDB.SQL

### ISSUE THREAD

**Issue by AntyaDev** [StereoDB/StereoDB#27]
https://github.com/StereoDB/StereoDB.SQL

**Comment by kant2002** [comment]
What about having that SQL part live in this repo? I suspect that I may want to have other datastructure then Dictionary eventually 😄 , at least I may persuade you to that, and it would be safe/easy.

**Comment by AntyaDev** [comment]
I was thinking of making these protocols replaceable/pluggable and keeping the Core Engine minimalistic.
For example, adding Redis requires me to add a whole new level with the TCP stack + storage layer, etc. I am not sure that this should be in the core engine. The same goes for different storage engines, etc.

**Comment by kant2002** [comment]
I agree with minimalistic core. Just that we have that in single repo, but separate projects. Would be much easier. We can rip further later on

**Comment by AntyaDev** [comment]
Yeah, that makes sense.
